//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Wizard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Details
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public int Amount { get; set; }
        public string Type { get; set; }
        public string Manufacture_Name { get; set; }
        public string Address { get; set; }
        public int No_Of_Retailer { get; set; }
        public string Online_Supplier { get; set; }
        public Nullable<long> Contact_No { get; set; }
        public int imageid { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
